# Generated by Django 3.2.5 on 2022-04-15 14:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('likeD', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=500)),
                ('path', models.FileField(upload_to='videos/', verbose_name='PATH')),
                ('thumbnail', models.FileField(blank=True, upload_to='thumbnails/')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('visibilty', models.CharField(choices=[('Public', 'Public'), ('Private', 'Private'), ('Draft', 'Draft'), ('None', 'None')], max_length=15)),
                ('dislikes', models.ManyToManyField(related_name='video_dislikes', through='likeD.VidDislikes', to=settings.AUTH_USER_MODEL)),
                ('hord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.hord')),
                ('likes', models.ManyToManyField(related_name='video_likes', through='likeD.VidLikes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Title must be greater than 2 characters')])),
                ('description', models.CharField(max_length=750)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('hord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.hord')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.video')),
            ],
        ),
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.hord')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.video')),
            ],
        ),
    ]
