# Generated by Django 3.2.5 on 2022-04-15 14:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('profile_image', models.ImageField(upload_to='images/profile/')),
                ('wall_paper', models.ImageField(upload_to='images/wall/')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsc_hord', to='account.hord')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('hord', 'user')},
            },
        ),
        migrations.CreateModel(
            name='SubHord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(5, 'Title must be greater than 5 characters')])),
                ('hord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.hord')),
            ],
        ),
        migrations.AddField(
            model_name='hord',
            name='subscribers',
            field=models.ManyToManyField(related_name='hoard_subscribers', through='account.Subscribers', to=settings.AUTH_USER_MODEL),
        ),
    ]
