# Generated by Django 3.2.5 on 2022-04-15 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('likeD', '0001_initial'),
        ('videos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vidlikes',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_video', to='videos.video'),
        ),
        migrations.AddField(
            model_name='viddislikes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='viddislikes',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disliked_video', to='videos.video'),
        ),
        migrations.AlterUniqueTogether(
            name='vidlikes',
            unique_together={('video', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='viddislikes',
            unique_together={('video', 'user')},
        ),
    ]
